version: '2'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        hostname: nginx
        networks:
          static-network:
            ipv4_address: 172.20.0.4
        volumes:
            - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - backend
            - frontend
    frontend:
        build:
          context: ./front
          dockerfile: dev.Dockerfile
    
        container_name: frontend
        hostname: frontend
        networks:
          static-network:
            ipv4_address: 172.20.0.3
        command: yarn start
        env_file: 
          - ./front/.env.sample
        volumes:
            - ./front:/app
            - /app/node_modules
        stdin_open: true
        ports:
            - "3000:3000"
    backend:
        build:
            context: ./libs
            dockerfile: dev.Dockerfile
        container_name: backend
        hostname: backend
        depends_on:
          - prolog
        networks:
          static-network:
            ipv4_address: 172.20.0.2
        volumes:
            - ./libs:/root/libs
        environment:
          -  "PROLOG_URL=http://172.20.0.5:8888"
        expose:
            - 80
        ports:
            - "5000:80"
 

    prolog:
        build: ./prolog
        container_name: Prolog
        hostname: prolog
        networks:
          static-network:
            ipv4_address: 172.20.0.5
        volumes:
           - ./prolog:/app
        ports:
          - 8888:8888
    
        

networks:
    static-network:
      ipam:
        config:
          - subnet: 172.20.0.0/16
            gateway: 172.20.0.1
